name: WebGL Build and Deploy

on:
  push:
    branches:
      - webgl

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      # 🛠️ Override actions/upload-artifact@v3 globally with v4
      - name: Override upload-artifact to v4
        uses: actions/upload-artifact@v4
        with:
          name: dummy
          path: README.md
        continue-on-error: true

      # 👇 Now Unity builder can use upload-artifact internally
      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      - name: Upload WebGL build to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/WebGL

      - name: Deploy WebGL to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
