name: WebGL Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - webgl

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Disable deprecated artifact upload
        run: |
          mkdir -p .github/actions
          echo '{}' > .github/actions/fake-upload-artifact.json

      - name: Build Unity WebGL (without internal artifact upload)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/WebGL

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2

